### ISSUE TITLE
Is there any macosx_xxx_arm64.whl in any previous release?

### ISSUE THREAD

**Issue by alanwilter** [cgohlke/imagecodecs#44]
It's about #6. Don't know why it's closed. I can't install it in my Mac Silicon. I still have `libaec.h` not found issue and no other version recommended had worked.

I'm browsing https://pypi.org/project/imagecodecs/#files and few previous versions and I haven't seen any macos arm64 wheel there.

**Comment by cgohlke** [comment]
#6 was closed because "pip3 install imagecodecs" works on macOS 10.15.

There are no binary wheels for ARM64, any OS. I don't have the resources to support those platforms and no one contributed build scripts, binaries, or hardware.

My understanding is that conda-forge provides binaries for some ARM64 platforms, including macOS.

**Comment by mkrupczak3** [comment]
Ran into this issue too. Let me know if there's any way I can help
