### ISSUE TITLE
could not import name 'jetraw_decode' from 'imagecodecs'

### ISSUE THREAD

**Issue by gil-c** [cgohlke/imagecodecs#66]
Hello,

I tried to read an image compressed with jetraw, but I have the following error message: 

`imagecodecs.imagecodecs.DelayedImportError: could not import name 'jetraw_decode' from 'imagecodecs'`

I am using imagecodecs 2023.3.16 from Pypi on Windows x64.

Should I install something else (e.g. jetraw binaries)?

**Comment by cgohlke** [comment]
That should have worked. Note that imagecodecs requires the [Visual C++ redistributable](https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170). Also make sure it's the right python.exe.

Instead of copying the DLLs, adding a call to `os.add_dll_directory(r'C:\Program Files\Jetraw\bin64')` before importing imagecodecs should also work.

**Comment by gil-c** [comment]
It worked! The `os.add_dll_directory` did the trick. Thank you very much for your help, and for all the work you put into developing this wonderful library.
